# Generated by Django 3.2.22 on 2023-10-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.stock'),
        ),
    ]
