# Generated by Django 3.2.22 on 2023-10-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock'),
        ),
    ]
