# Generated by Django 3.2.22 on 2023-10-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231028_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock', to='core.stock'),
        ),
    ]
